spring:
  cloud: 
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Referer"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
      routes:
        - id: identity-service
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
            
        - id: products-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/** 
        
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/transactionService/**

            
        - id: carts-service
          uri: http://localhost:8080
          predicates:
            - Path=/cart/**, /orders/**
            
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true